### ISSUE TITLE
how to associate my github account with my early swap commits?

### ISSUE THREAD

**Issue by dckc** [linkeddata/swap#1]
I think TimBL tried to connect pre-git committers with the right email addresses or something but I didn't respond in time or something.

Any suggestions on how to make the connection after-the-fact?

**Comment by timbl** [comment]
Good question..

**Comment by timbl** [comment]
Now, see https://scottmathson.com/blog/2019/02/13/combine-merge-github-user-accounts-keeping-git-commit-history/?ref=stack-overflow

**Comment by dckc** [comment]
I tried adding that address to my github account, but I don't think it helped.

Oh well.

"consistency is the hobgoblin of small minds" or something like that :)

**Comment by timbl** [comment]
:-)
"Any emails that you’ve been actively using in your local git configuration should be added to your GitHub account email settings in order for commits to be re-attributed and added to graph." .. maybe it will take a while for github to propagate stuff
